const ACCESS_TOKEN_EXPIRE_TIME = "1m"
const REFRESH_TOKEN_EXPIRE_TIME = "5m"
const ACCESS_TOKEN_STRING =  "accessToken"
const REFRESH_TOKEN_STRING =  "refreshToken"
const ACCESS_TOKEN_MAX_AGE = 60000; // 60 seconds
const REFRESH_TOKEN_MAX_AGE = 300000 // 5 minute


module.exports = {
    ACCESS_TOKEN_EXPIRE_TIME,
    REFRESH_TOKEN_EXPIRE_TIME,
    ACCESS_TOKEN_STRING,
    REFRESH_TOKEN_STRING,
    ACCESS_TOKEN_MAX_AGE,
    REFRESH_TOKEN_MAX_AGE,
}